### ISSUE TITLE
Publish artifact to Maven Central

### ISSUE THREAD

**Issue by Odyldzhon** [nielsbasjes/dsmr-tools#1]
Good Day Niels Basjes!
Thank you very much for your wonderful project. Do you plan to publish it somewhere for example to Maven Central? It will be useful for someone like me who are interesting in using DSMR parser in own project.

**Comment by nielsbasjes** [comment]
Yes, publishing it to Maven central is fine by me.

The main reason I hadn't done that yet is simply because I think it needed some testing first.

Can you confirm if it works for you? 
And if not, what needs to be fixed?

**Comment by Odyldzhon** [comment]
Actually I have test only parser and so far I didn't saw any issue.
Anyway I can contribute in case I will find something.
Thank you!

**Comment by yholkamp** [comment]
@nielsbasjes while I cannot confirm the full project works the `dsmr-parser` has been working quite well for me over the course of a couple of weeks. Since I'm not using Nifi and I also wanted to include stats from a couple of other sources so I've just cherry picked that part. So obviously I think it'd be great if you could publish the project artefacts on Maven central to make it available for usage in other projects.

**Comment by nielsbasjes** [comment]
Understood. I'll get on it.

**Comment by nielsbasjes** [comment]
Step 1 almost done: I now have a the CI build and most of the quality checks I want in place.

**Comment by nielsbasjes** [comment]
I have just released everything to maven central.
